name: Run Tests

on: [ push,workflow_dispatch,workflow_call,pull_request ]

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Run schema validation against JSON file with test cases and execute example tests
        run: |
          mvn test